version: "3.9"

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4173:4173" # Maps port 3000 on the host to port 3000 in the container
    volumes:
      - ./src:/app/src # Syncs your source code for hot-reloading
      - /app/node_modules # Ensures node_modules inside the container do not sync with the host
    environment:
      - CHOKIDAR_USEPOLLING=true # Required for hot-reloading to work reliably inside Docker
    stdin_open: true
    tty: true
